global:
  scrape_interval: 3s

scrape_configs:
  # Monitor Mac
  - job_name: 'node_exporter_mac'
    static_configs:
      - targets: ['node_exporter:9100']

  # Uncomment and adjust IP when Raspberry Pi is online
  # - job_name: 'node_exporter_rpi'
  #   scrape_interval: 1s
  #   static_configs:
  #     - targets: ['172.20.10.10:9100']